### ISSUE TITLE
New version return wrong name for function

### ISSUE THREAD

**Issue by andrew-mai-laidon** [mrbandler/cds2types#17]
I'm having an issues with 2.7.0 version.
In my cds, I have a function like this:
function getBusinessModelMetadata() returns String;
In 2.6.2 version, this will create an interface:
export enum FuncGetBusinessModelMetadata {
        name = "getBusinessModelMetadata"
    }
But, in 2.7.0, it will return:
export enum FuncGetBusinessModelMetadata {
        name = "GetBusinessModelMetadata"
    }
The first letter is uppercase, which mess up the cds routing handler.

**Comment by HeneryHawk** [comment]
Hi @andrew-mai-laidon 

Thanks for reporting the bug.
I have released a new version (2.7.1-beta.0). Can you please test briefly with this version if the bug is fixed?

Regards
Simon

**Comment by andrew-mai-laidon** [comment]
Hi @HeneryHawk ,

I can confirm that the bug is fixed with 2.7.1-beta.0.

**Comment by HeneryHawk** [comment]
Hi @andrew-mai-laidon 

i released the new version 2.7.1.

Regards
Simon
