### ISSUE TITLE
version number in cli.ts

### ISSUE THREAD

**Issue by mocotrah** [mrbandler/cds2types#21]
Hi,
If I understand correctly the actual version is 2.7.1.
When I launch a cds2types -V the reported version is 2.6.1.
Shouldn't you update the version number in cli.ts everytime you release a new version?
https://github.com/mrbandler/cds2types/blob/1c55649c8549397a3fbd30c7fd613d1420c0a400/src/cli.ts#L12

**Comment by HeneryHawk** [comment]
Hi @mocotrah,

This will be fixed with the next release.
Thank you for reporting this issue.

Regards
Simon
