### ISSUE TITLE
aspects and interfaces

### ISSUE THREAD

**Issue by mocotrah** [mrbandler/cds2types#23]
Given the following entities:
```
aspect Chair {
  color: String;
}
entity Table {
  key id : String;
  chairsAround :  Composition of many Chair;
}
```
after launching cds2types we get 
```
export interface IChairsAround {
    up_?: ITable;
    up__id?: string;
    color: string;
  }

  export interface ILastConsumption {
    up_?: ITransactions;
    up__id?: number;
    value: number;
    timestamp: Date;
  }
```
There is no IChair interface created.
Is this the normal behavior?

**Comment by HeneryHawk** [comment]
Hi @mocotrah,
yes, this is the desired behavior.

Aspects can be attached to an entity (e.g. the aspect temporal). So they extend the entity with their fields. You have used an aspect as a type for a property.
In both cases, no separate interface is needed for the aspect.
In case 1, the entity to which the aspect is attached is extended with the fields of the aspect.
In case 2, a separate interface is created for the type of the property with the fields of the aspect and other necessary fields (up_, up__id).

There is no need for a separate interface for the aspect, therefore no interface is created here.

Regards
Simon

**Comment by mocotrah** [comment]
thank you for clarification. You can close the issue.
