### ISSUE TITLE
Feature: Add return type for Actions to entities.ts compilation

### ISSUE THREAD

**Issue by mattreddy3** [mrbandler/cds2types#3]
Hi! Love the initiative, and even as a Typescript novice I am finding it easy and useful to utilize this library.

I am wondering if we can do anything about getting return parameters in actions?

Current state:
A CDS configuration of:
```typescript
service SchedulerService {
    action runJob(entityName : Integer) returns String;
...
```
yields an `entities.ts` entry of
```typescript
export namespace SchedulerService {
    export enum ActionRunJob {
        name = "runJob",
        paramEntityName = "entityName"
    }
    export interface IActionRunJobParams {
        entityName: number;
    }
...
```

Ideal state:
The same CDS configuration would yield an `entities.ts` entry of:
```typescript
export namespace SchedulerService {
    export enum ActionRunJob {
        name = "runJob",
        paramEntityName = "entityName"
    }
    export interface IActionRunJobParams {
        entityName: number;
    }
    export type ActionRunJobReturn = string // or other type reference according to .cds file
```

**Comment by mrbandler** [comment]
Hi @mattreddy3,

glad you like it!

That's a great idea, especially for more complex return types.

I don't think this would be hard to add to the current code base aswell, I'll implement it on my next maintance release.

Thank you for suggesting it!

**Comment by mrbandler** [comment]
Alrighty, I just published a new version (v2.5.1) which includes the requested change.
There will now be type aliases generated for action and function return types.

For this given CDS:

```cds
service ActionsAndFunctions {
    action runJob(entityName : Integer) returns String;
}
```

it generates the following Typescript:

```typescript
export namespace SchedulerService {
    export enum ActionRunJob {
        name = "runJob",
        paramEntityName = "entityName",
    }

    export interface IActionRunJobParams {
        entityName: number;
    }

    export type ActionRunJobReturn = string;

    export enum Entity {}

    export enum SanitizedEntity {}
}

export enum Entity {}

export enum SanitizedEntity {}\
```

Let me know if you encounter any problems with the new version, I will close this issue now.

**Comment by mattreddy3** [comment]
Awesome, thanks! i'll test it out and let you know if i have any problems

**Comment by mrbandler** [comment]
I pushed a little hotfix just now, as the entity enums had a bug and were generated with the interface prefix append.
New version is v2.5.1.

**Comment by mattreddy3** [comment]
Ah, nice - was literally writing about that :)
 
![image](https://user-images.githubusercontent.com/14957827/98451960-43482f00-214b-11eb-94dc-92653a0cec78.png)
