### ISSUE TITLE
Module Syntax not supported for ESM2015

### ISSUE THREAD

**Issue by szymarcus** [mrbandler/cds2types#31]
Hey folks,

thanks for this convenience script. On using it in my setup I noticed that I get an error from linter because the `export namespace <PACKAGE_NAME>` is not supported by ESM2015.

The exact error I am getting from the linter goes as follows:

`namespace com.aldi.supplierportal
ES2015 module syntax is preferred over custom TypeScript modules and namespaces.`

I think this library should switch to the new syntax `declare namespace` Syntax in the future.

Further Reference:

https://typescript-eslint.io/rules/no-namespace/

**Comment by alumni** [comment]
More and more libraries are becoming ESM-only, even axios dropped CommonJS support. It would be nice to have this working with ESM.

**Comment by thisisevanfox** [comment]
Closed with v3.0.0 (#45).
