### ISSUE TITLE
Feature: custom type

### ISSUE THREAD

**Issue by mattreddy3** [mrbandler/cds2types#4]
Hi there,

Another one I'm hoping is relatively simple

There are times in my `schema.cds` where I define custom types: 
```typescript
define type AssetID : String(8);
entity ScheduleItem : cuid, tenant {
    OrderType  : String(4);
    AssetID    : AssetID;
}
```
Currently, this yields an `entities.ts` like:
```typescript
export interface IAssetID {
}
export interface IAssetSchedule extends redfig.schedulercockpit.ITenant, ICuid {
    AssetID;
    EndTime: Date;
}
```
Notice that the AssetID now has lost its typing and is typed to `any`. Wondering if it is easy to modify simple CDS types to export as: (nomenclature can be better I'm sure)
```typescript
export type AssetID = string;

export interface IAssetSchedule extends redfig.schedulercockpit.ITenant, ICuid {
    AssetID: AssetID;
    EndTime: Date;
}
```
I'm hoping that it's easy enough to distinguish between an enum CDS type and a simple CDS type.

**Comment by mrbandler** [comment]
Hi @mattreddy3, I did not answer here directly but I implemented all possible type aliases in the new release (v2.5.1).

For the following CDS:

```cds
type AssetID : String(8);
entity ScheduleItem {
    OrderType  : String(4);
    AssetID    : AssetID;
}
```
it now generates the following Typescript: 

```typescript
export type AssetID = string;

export interface IScheduleItem {
    OrderType: string;
    AssetID: AssetID;
}
```

I am really happy you caught this, as I have been waiting for someone else to use it in production to catch syntax edge cases I did not need up until that point or just simply forgot.

To that extend I added all possible (don't take my word for it, the SAP documentation is not always in the best state) type alias forms.

### Simple Type Alias

```cds
type AssetID : String(8);
```

```typescript
export type AssetID = string;
```
### Array Type Aliase

**With Primitives**

```cds
type Numbers : many Integer;
```

```typescript
export type Numbers = number[];
```

**With Type/Entity**

```cds
entity Foo {
    bar: String;
}

type Foos : many Foo;
```

```typescript
export interface IFoo {
    bar: string;
}

export type Foos = IFoo[];
```

**With Inline Type**

```cds
type Bars : many { foo: String; };
```

```typescript
export type Bars = { foo: string }[];
```

> For completeness sake I'll add the other two type declarations, which already worked in the previous version.

### Enum Type

```cds
type Gender : Integer enum {
    NonBinary;
    Male;
    Female;
}
```

```typescript
export enum Gender {
    NonBinary,
    Male,
    Female,
}
```

### User Type

```cds
type Person {
    name: String;
    age: Integer;
}
```

```typescript
export interface IPerson {
    name: string;
    age: number;
}
```

**Comment by mattreddy3** [comment]
Yes, I noticed you squashed both bugs with the update
