### ISSUE TITLE
Is it possible to use **array of** for the input of a action

### ISSUE THREAD

**Issue by mrbandler** [mrbandler/cds2types#9]
Is it possible to use **array of** for the input of the action, currently, this will return error:
**Error: Cannot read property 'ref' of undefined** 
`action createTemplate(template : Templates, templateSections : array of TemplateSections, templateSectionFields : array of TemplateSectionFields, templateCopied : String) returns CommonActionOutput;`

_Originally posted by @andrew-mai-laidon in https://github.com/mrbandler/cds2types/issues/7#issuecomment-886063109_

**Comment by andrew-mai-laidon** [comment]
Is there any update on this issues?
If possible, I will try to help, which part of the code that I should take a look to detect the problems?

**Comment by HeneryHawk** [comment]
Hi @andrew-mai-laidon 

I started working on the topic yesterday and finished a first prototype.

I'll get back to you later.

regards
Simon

**Comment by HeneryHawk** [comment]
Hi @andrew-mai-laidon

I have published a beta version (2.6.2-beta.0).
If you like, you can test with it and give a short feedback if the bug is fixed.

Regards
Simon

**Comment by andrew-mai-laidon** [comment]
Hi, the beta version was able to build the type **array of** for the action!
Thanks a lot!

**Comment by HeneryHawk** [comment]
Hi @andrew-mai-laidon,

I released version [2.6.2](https://github.com/mrbandler/cds2types/releases/tag/v2.6.2) today which includes the enhancements.

Regards
Simon
